name: ❓ Question
description: Vous voulez comprendre quelque chose ou demander de l'aide. / Ask for help or clarification.
title: "[Question] "
labels: ["question", "triage"]
body:
  - type: textarea
    id: question
    attributes:
      label: Votre question / Your question
      placeholder: "Comment ça marche, le système de claim sur Survie ?"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Contexte / Context
      description: Ce que vous avez déjà essayé ou lu, le serveur concerné, etc.
